name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.3.1
      with:
        branch: gh-pages  # El branch al que desplegar (GitHub Pages)
        folder: build  # La carpeta que se va a desplegar
        token: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub para autorización

